#!/bin/bash

set -e

if [ ! -e "$vaultpass_abspath" ]; then
    echo -e "${yellow}Ansible Vault password file not found at${normal} ${real_vaultpass_abspath}"

    echo "Do you want to download it from 1password?"
    echo -e "Do you want to try downloading it from 1password? [y/n]: \c"
    read download_vault_password

    if [ "$download_vault_password" = "y" ] || [ "$download_vault_password" = "yes" ]; then
        echo -e "Enter 1password subdomain (e.g. xxx.1password.com): \c"
        read op_subdomain

        echo -e "Enter 1password email: \c"
        read op_email

        if grep $op_subdomain ~/.op/config 1>/dev/null; then
            eval $(op signin $op_subdomain)
        else
            eval $(op signin $op_subdomain $op_email)
        fi

        mkdir -p $(dirname $vaultpass_abspath)
        echo "Downloading vault password file ansible_vault_password_$cluster_id..."
        if op get document ansible_vault_password_$cluster_id > $vaultpass_abspath; then
            echo "Vault password file saved to $real_vaultpass_abspath"
        else
            rm -rf $vaultpass_abspath
            echo "Error downloading password file please fix the error before retrying"
        fi

    else
        echo "Not attempting to download from 1password."
    fi

fi
